
"use client";

import { useState, useEffect } from 'react';
import { UploadForm, type InputType } from '@/components/upload-form';
import { ResultsView } from '@/components/results-view';
import { useToast } from "@/hooks/use-toast";
import { Skeleton } from './ui/skeleton';
import { Card, CardContent } from './ui/card';

// Mock server actions
const processText = async (input: { documentText: string; text: string }): Promise<{ summary: string; keywords: string; notes: string; }> => {
  console.log("Processing text:", input.text.substring(0, 50) + "...");
  await new Promise(resolve => setTimeout(resolve, 1500));
  return {
    summary: `This is a mock summary for the provided text. In a real application, this would be a concise overview generated by an AI model, focusing on the key points and main ideas of the document.`,
    keywords: 'Mock, Frontend, Analysis, Demo, React, Next.js, UI, UX',
    notes: '• This is a frontend-only demonstration.\n• AI processing is simulated with a delay.\n• The UI is built with ShadCN and Tailwind CSS.\n• Data is mocked and not persisted.'
  };
};

const processVideo = async (input: { videoDataUri: string }): Promise<{ transcription: string }> => {
  console.log("Processing video...");
  await new Promise(resolve => setTimeout(resolve, 3000));
  return {
    transcription: "This is a mock transcription of the uploaded video. In a production app, this would be the full text content of the video, generated by a speech-to-text AI model. This allows the video content to be searchable, summarizable, and analyzable just like a text document."
  };
};

export type ProcessedContent = {
  id?: string;
  sourceType: InputType;
  sourceText: string;
  sourceTitle:string;
  summary?: string;
  keywords?: string;
  notes?: string;
  transcription?: string;
  createdAt?: any;
};

type DashboardClientProps = {
  selectedSession: ProcessedContent | null;
  onNewSession: () => void;
  onSessionCreated: (session: ProcessedContent) => void;
};


export function DashboardClient({ selectedSession, onNewSession, onSessionCreated }: DashboardClientProps) {
  const [processedContent, setProcessedContent] = useState<ProcessedContent | null>(selectedSession);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    setProcessedContent(selectedSession);
  }, [selectedSession]);


  const handleTextAnalysis = async (text: string, title: string) => {
    if (!text || !title) {
      toast({
        variant: "destructive",
        title: "Missing Input",
        description: "Please provide both a title and content to analyze.",
      });
      return;
    }
    setIsLoading(true);
    setProcessedContent(null);
    try {
      const result = await processText({documentText: text, text: text});
      const newSessionData: ProcessedContent = {
        sourceType: 'text',
        sourceText: text,
        sourceTitle: title,
        ...result,
      };
      onSessionCreated(newSessionData);
    } catch (error) {
      console.error(error);
      toast({
        variant: "destructive",
        title: "Analysis Failed",
        description: "Could not process the text. Please try again.",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleVideoAnalysis = async (videoFile: File, title: string) => {
    if (!videoFile) {
      toast({
        variant: "destructive",
        title: "Error",
        description: "Please select a video file.",
      });
      return;
    }
    setIsLoading(true);
    setProcessedContent(null);

    try {
      const videoDataUri = await new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = (event) => {
          if (event.target?.result) {
            resolve(event.target.result as string);
          } else {
            reject(new Error("Failed to read video file."));
          }
        };
        reader.onerror = (error) => {
          reject(error);
        };
        reader.readAsDataURL(videoFile);
      });
      
      const result = await processVideo({ videoDataUri });
       const newSessionData: ProcessedContent = {
        sourceType: 'video',
        sourceText: 'Video content not displayed', 
        sourceTitle: title,
        transcription: result.transcription,
      };

      // Since video only gives transcription, we can generate the rest
      const textAnalysisResult = await processText({documentText: result.transcription, text: result.transcription});

      const finalSessionData = {
        ...newSessionData,
        ...textAnalysisResult,
      }

      onSessionCreated(finalSessionData);
    } catch (error) {
      console.error(error);
      toast({
        variant: "destructive",
        title: "Transcription Failed",
        description: "Could not transcribe the video. Please try again.",
      });
    } finally {
      setIsLoading(false);
    }
  };

  if (isLoading) {
    return (
       <div className="grid gap-6">
        <Card>
          <CardContent className="p-6 space-y-4">
             <Skeleton className="h-8 w-1/2" />
             <Skeleton className="h-40 w-full" />
             <Skeleton className="h-8 w-24" />
          </CardContent>
        </Card>
      </div>
    );
  }

  if (processedContent) {
    return <ResultsView content={processedContent} onNewSession={onNewSession} />;
  }

  return (
    <div className="space-y-6">
       <div className="flex flex-col gap-2 rounded-xl border bg-card p-6 text-card-foreground shadow">
        <h1 className="font-headline text-3xl font-bold">Welcome back!</h1>
        <p className="text-muted-foreground">
          Start a new study session by providing your materials below.
        </p>
      </div>
      <UploadForm onTextSubmit={handleTextAnalysis} onVideoSubmit={handleVideoAnalysis} isProcessing={isLoading} />
    </div>
  );
}
